-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 13:43:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_grade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_grade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_grade` DEFAULT CHARACTER SET utf8 ;
USE `mydb_grade` ;

-- -----------------------------------------------------
-- Table `mydb_grade`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_grade`.`Department` (
  `dno` INT NOT NULL AUTO_INCREMENT,
  `dname` VARCHAR(45) NOT NULL,
  `dtel` VARCHAR(45) NOT NULL,
  `doffice` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_grade`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_grade`.`Student` (
  `ssn` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `mobile` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Department_dno` INT NOT NULL,
  PRIMARY KEY (`ssn`),
  INDEX `fk_Student_Department_idx` (`Department_dno` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Department`
    FOREIGN KEY (`Department_dno`)
    REFERENCES `mydb_grade`.`Department` (`dno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_grade`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_grade`.`Professor` (
  `ssn` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `mobile` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Department_dno` INT NOT NULL,
  PRIMARY KEY (`ssn`),
  INDEX `fk_Professor_Department1_idx` (`Department_dno` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Department1`
    FOREIGN KEY (`Department_dno`)
    REFERENCES `mydb_grade`.`Department` (`dno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_grade`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_grade`.`Subject` (
  `sub_no` INT NOT NULL AUTO_INCREMENT,
  `sname` VARCHAR(45) NOT NULL,
  `grade` INT NOT NULL,
  `room` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `Professor_ssn` INT NOT NULL,
  PRIMARY KEY (`sub_no`, `Professor_ssn`),
  INDEX `fk_Subject_Professor1_idx` (`Professor_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Subject_Professor1`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `mydb_grade`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_grade`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_grade`.`Course` (
  `cno` INT NOT NULL AUTO_INCREMENT,
  `Student_ssn` INT NOT NULL,
  `Subject_sub_no` INT NOT NULL,
  `Subject_Professor_ssn` INT NOT NULL,
  `grade` INT NULL,
  PRIMARY KEY (`cno`, `Subject_sub_no`, `Subject_Professor_ssn`),
  INDEX `fk_Course_Student1_idx` (`Student_ssn` ASC) VISIBLE,
  INDEX `fk_Course_Subject1_idx` (`Subject_sub_no` ASC, `Subject_Professor_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Student1`
    FOREIGN KEY (`Student_ssn`)
    REFERENCES `mydb_grade`.`Student` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Subject1`
    FOREIGN KEY (`Subject_sub_no` , `Subject_Professor_ssn`)
    REFERENCES `mydb_grade`.`Subject` (`sub_no` , `Professor_ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_grade`.`Charge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_grade`.`Charge` (
  `chr_no` INT NOT NULL AUTO_INCREMENT,
  `Student_ssn` INT NOT NULL,
  `Professor_ssn` INT NOT NULL,
  `semester` VARCHAR(45) NULL,
  PRIMARY KEY (`chr_no`, `Student_ssn`, `Professor_ssn`),
  INDEX `fk_Charge_Student1_idx` (`Student_ssn` ASC) VISIBLE,
  INDEX `fk_Charge_Professor1_idx` (`Professor_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Charge_Student1`
    FOREIGN KEY (`Student_ssn`)
    REFERENCES `mydb_grade`.`Student` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Charge_Professor1`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `mydb_grade`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
